### ISSUE TITLE
Double-precision mystery

### ISSUE THREAD

**Issue by neurolabusc** [fxcoudert/gfortran-for-macOS#13]
First of all, thanks for all the work that has gone into this. I realize this is an experimental release, so maybe this is premature issue. However, I would be interested if @iains or others have any thoughts. I created a simple fortran benchmark [as part of a review of the M1](https://github.com/neurolabusc/AppleSiliconForNeuroimaging). It is likely that this is memory-bandwidth rather than computation limited (common in my field). Regardless, the M1 performance is very promising, but the double-precision performance shows something odd.

Running the attached program shows that the M1 is very fast, but the 64-bit shows variability 
`gfortran -O3 -o f400 fortran400.f95; ./f400`

- i5-8259u MacBook Pro
  - sqrt32 min/mean  296.547  303.131
  - sqrt64 min/mean  334.015  353.714
- 3900x Ubuntu Desktop
  - sqrt32 min/mean   97.050   97.616
  - sqrt64 min/mean  276.307  276.490
- M1 MacBook Air
  - sqrt32 min/mean   42.773   44.919
  - sqrt64 min/mean   85.466  217.514

My code always ignores the first run to deal with cache and warmup variability. However, reporting the time per repetition shows the first runs are slow - not what one expects from thermal throttling and note this was run with the laptop plugged in. This is not a memory alignment issue, as all arrays are reused for all runs, so have the same alignment.

```
gfortran -O3 -o f400 fortran400.f95; ./f400
Time =  732.765 ms
Time =  106.665 ms
Time =   86.964 ms
Time =   86.844 ms
Time =   86.710 ms
 Reporting minimum time for            5  tests, array size   269568000
sqrt64 min/mean   86.710  219.990
```
This behavior is not seen with C code compiled using Apple's Clang 12.0:

```
 Reporting minimum time for 4 repetitions with 1 threads
sqrt32: min/mean	43	43	ms
sqrt64: min/mean	85	91	ms
```

Is there any explanation for this behavior? I know double-precision arrays are common with Python Numpy and R, both of which rely on Fortran compilers. Beyond this, this looks very promising.

[fortran400.f95.txt](https://github.com/fxcoudert/gfortran-for-macOS/files/5648894/fortran400.f95.txt)
[c400.cpp.txt](https://github.com/fxcoudert/gfortran-for-macOS/files/5648896/c400.cpp.txt)

**Comment by fxcoudert** [comment]
I'm seeing the same effect on my Intel 2018 MacBook Pro laptop:

```
$ gfortran -O3 fortran400.f95 && ./a.out
Time32 =  173.558 ms
Time32 =  141.418 ms
Time32 =  141.108 ms
Time32 =  139.671 ms
Time32 =  139.855 ms
 Reporting minimum time for            5  tests, array size   269568000
sqrt32 min/mean  139.671  147.122
Time64 = 1333.888 ms
Time64 =  284.087 ms
Time64 =  280.822 ms
Time64 =  276.900 ms
Time64 =  271.395 ms
 Reporting minimum time for            5  tests, array size   269568000
sqrt64 min/mean  271.395  489.418
```

**Comment by iains** [comment]
(disclaimer, I've not looked at the code).. I wonder if there's some start-up penalty for the first use of a lazy symbol from a dylib - that ought to be irrelevant if you do a complete iteration and discard the output - which is what I think you said .

Anyway - lIkewise, for example, I see this on Intel i7 (Darwin16 / macOS 10.12).
$ ./t
Time32 =  369.096 ms
Time32 =  309.173 ms
Time32 =  308.782 ms
Time32 =  301.036 ms
Time32 =  304.679 ms
 Reporting minimum time for            5  tests, array size   269568000
sqrt32 min/mean  301.036  318.553
Time64 = 3390.699 ms
Time64 =  663.039 ms
Time64 =  663.781 ms
Time64 =  661.287 ms
Time64 =  660.414 ms
 Reporting minimum time for            5  tests, array size   269568000
sqrt64 min/mean  660.414 1207.844

====

with yesterday's build of the Arm64 compiler + the current 11.1 beta (on a DTK) .. so all subject to "maybe" somewhat less ... 

$ ./t
Time32 =  106.264 ms
Time32 =   75.750 ms
Time32 =   75.507 ms
Time32 =   72.736 ms
Time32 =   72.859 ms
 Reporting minimum time for            5  tests, array size   269568000
sqrt32 min/mean   72.736   80.623
Time64 =  218.995 ms
Time64 =  147.616 ms
Time64 =  147.636 ms
Time64 =  147.667 ms
Time64 =  147.639 ms
 Reporting minimum time for            5  tests, array size   269568000
sqrt64 min/mean  147.616  161.911

**Comment by iains** [comment]
and GCC-11 (G++)
g++ /source/test/cxx/c400.cpp -O2 -o t -fopenmp

Intel i7 / macOS 10.12 
$ ./t  5 5 
c400 (with OpenMP )  GCC 
usage: omp [reps] [threads]
example: omp 4 4
 Reporting minimum time for 5 repetitions with 5 threads
sqrt32: min/mean	109	116	ms
sqrt64: min/mean	210	218	ms

arm64 unknown maOS 11.1beta

$ ./t 5 5
c400 (with OpenMP )  GCC 
usage: omp [reps] [threads]
example: omp 4 4
 Reporting minimum time for 5 repetitions with 5 threads
sqrt32: min/mean	69	69	ms
sqrt64: min/mean	75	75	ms

**Comment by iains** [comment]
OK.. so I poked around at the code (limping heavily, since I'm not fluent in Fortran) .. and tried things like making one complete edition of all the calls before the main loop is entered.  No change - there really seems to be some effect on the first iteration of the loop.  I didn't stop to look at the generated code yet.

Anyway,  this manifests on more than one target (including on mature back-ends) so I think it needs moving to a GCC gfortran PR *phew* ...

**Comment by iains** [comment]
I don't, however, see it on powerpc64-linux-gnu, so it might be a fortran+darwin issue.

**Comment by iains** [comment]
problem manifests : 

power64-linux-gnu - (Power9) -  no
x86_64-linux-gnu - (Xeon(R) E5-2660) no

x86_64-apple-darwin20 (Core(TM) i5-8500B) - no
x86_64-apple-darwin19 (Xeon W - AVX512) - no
x86_64-apple-darwin19 (Core(TM) i7-4578U) - no
x86_64-apple-darwin18 (Core(TM) i7-4578U) -  10%
x86_64-apple-darwin17 (Xeon(R) X5690) - no
x86_64-apple-darwin16 (VM) - not repeatable but (10 - 1000% on a cold start)
x86_64-apple-darwin16 (Core(TM) i7-7700HQ) - not repeatable but (10 - 200% on a cold start)

arm64-apple-darwin20 (unknown) - 5 to 10% depending.

I suspect (unproven hunch) that some of this is down to some cache state [e.g. dyld cache] - if you try (on an Intel machine, for example) running the code from cold - the effect might manifest, but then run it two or three times in succession and the percentage drops to ≈ 5..10% for the first iteration.  We have seen these kinds of effects with DYLD_LIBRARY_PATH and caches for tool lookups.

For some platforms, including some instances on macOS, I see no effect at all (sometimes even the first iteration is fastest)

I also tried reconfiguring GCC to be specific about the target CPU (rather than using the Darwin default) - that didn't seem to make too much difference either.

... in short, this is probably going to be tricky to chase.

**Comment by neurolabusc** [comment]
@iains I am happy to close this. Alternatively, happy to have you post at a relevant location where others can investigate.

Clearly, it is not specific to the M1 architecture. As you note, it seems specific to macOS, and is seen in early releases of Fortran as well. I did try seeing if running without networking would change behavior (e.g. due to trustd verification). I also tried a static build (gfortran -O3 -o f400 fortran400.f95 -dynamiclib -lgfortran -static-libgfortran /usr/local/gfortran/lib/libgfortran.a). Neither have an impact. 

I did compile and test a few other Fortran projects, and they seem in good shape. Thanks again for your work.

**Comment by iains** [comment]
at present, I have no further comment (nor indeed any specific idea how to debug).

* Note that the effect is most dramatic on Darwin variants on portables (I haven't been able to test whether similar effects might be visible on a Linux laptop). 

* I have seen the effect even on a Power9 Linux machine (but at a very much lower level)

It would not surprise me if Darwin on portable platforms exhibited the most aggressive power management.

Do you repeat my observation that repeated runs produce smaller distributions in runtimes?
and that leaving the platform quiet for a while then produces the original behaviour?

**Comment by neurolabusc** [comment]
Yes, I have also see the same effect: running the benchmark repeatedly hides the penalty, waiting elicits it. So it seems consistent with your notion that this has something to do with an energy efficient state, though no penalty is seen for the analogous C code. Thanks again for your insightful comments. I will close this issue.
