### ISSUE TITLE
Issue with gfortran 11 -lquadmath not found

### ISSUE THREAD

**Issue by AMenafoglio** [fxcoudert/gfortran-for-macOS#24]
I installed xcode and the latest release of gfortran for the macOS Big Sur Version 11.2.3 (Chip Apple M1). 

I'm trying to install a package in R and I get the following error:
```
ld: library not found for -lquadmath
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [fdagstat.so] Error 1
```

I have seen previous discussions on the topic suggesting to install previous versions of gfortran but this is not possible on my machine.

Do you have any suggestion on how to solve the problem?

Thank you

**Comment by stephens999** [comment]
I had the same issue (on an intel mac). I fixed it by going back to gfortran release 10.2 because that was an option for me.

**Comment by fxcoudert** [comment]
The R package shouldn't pass `-lquadmath` on an Apple M1 system.

**Comment by stephens999** [comment]
mine isn't an M1 system...  
are you implying gfortran 11 should only be used on M1 system?

**Comment by fxcoudert** [comment]
@AMenafoglio is using an ARM chip, and there `-lquadmath` should not be used. I was answering his issue.

For an Intel chip, there is an Intel package, and it should find `-lquadmath`. I'd need to see full information to debug the issue.

**Comment by stephens999** [comment]
thanks. What info do you need? I now have a working setup (after removing
gfortran 11 and installing gfortran 10.2) so it remains to be see whether
I can reproduce the problem, but will try if it would be helpful to you.

**Comment by AMenafoglio** [comment]
Hi, thanks for the support. The problem was probably in my installed version of R, not directly in the package. I solved the issue by editing the Makeconf of R and removing -lquadmath from the variable FLIBS. 

Thanks a lot again for the help!

**Comment by Chikuwaq** [comment]
Hi, does anyone know whether the fortran REAL(16) and COMPLEX(16) is going to be available soon on an M1 Mac? 

I installed gcc-m1-bin.tar.gz from [HPC Mac OS X](http://hpc.sourceforge.net) and try to compile my fortran codes that contain 16-bits variables. The compiler complains:
`Error: Kind 16 not supported for type REAL at (1)
`
gcc version: 11.0.0 20201128 (experimental)
macOS: Big Sur 11.3.1 Apple Silicon

[gcc.gnu.org](https://gcc.gnu.org/onlinedocs/gfortran/KIND-Type-Parameters.html) says 16-bits are not available on all systems. It's been 6 months since the update and I hope they become available soon.

**Comment by fxcoudert** [comment]
@Chikuwaq There is no current, solid plan for implementation. If you want, you can contribute (or pay someone to contribute) that functionality to GCC.

**Comment by Chikuwaq** [comment]
@fxcoudert Thanks for the info. I'll discuss with my colleagues.
