### ISSUE TITLE
Package gfortran without other binaries?

### ISSUE THREAD

**Issue by TidbitSoftware** [fxcoudert/gfortran-for-macOS#56]
First off, thank you for putting in all the time and effort to provide and support this distributable.

Could you provide `gfortran` without the other packages binaries (e.g. `gcc`), or is it dependent on them? We use `gfortran` to compile a number of external packages (e.g. PETSc) as well as some modules of our own codebase. On a Silicon-based Mac and using version 12.2, a small number of our regression tests fail with large deltas when compared to our archived test results. We found that if we ensure that the Xcode copy of `gcc` is used to compile, the tests pass as expected. We didn't realize at first that `gcc` was distributed with your package, and we understand that we could modify our environment setup so that the `bin` directory shows up later in the path, but I wonder if it's even necessary to ship with `gcc` and wonder what other issues might go unnoticed. Thanks for your time!

**Comment by fxcoudert** [comment]
It's not necessary to ship gcc and other compiler binaries, but users have been requesting them, and so I ship the whole compiler series. You can control the PATH, or remove the unwanted binaries, to achieve your goal.

You could also call `cc` or `clang` instead of `gcc`, since the compiler on macOS is clang anyway.
